#!/bin/sh

# Select correct binary based on architecture
ARCH=$(dpkg --print-architecture)
cd /opt/ed-lvd/
if [ "$ARCH" = "arm64" ]; then
    ln -sf lvd-monitor-arm64 lvd-monitor
    rm -f lvd-monitor-armhf
elif [ "$ARCH" = "armhf" ]; then
    ln -sf lvd-monitor-armhf lvd-monitor
    rm -f lvd-monitor-arm64
fi

start(){
    systemctl daemon-reload
    systemctl enable lvd-detect.service
    systemctl start lvd-detect.service
}

start

exit 0