#!/bin/sh

BITS=$(getconf LONG_BIT)

if [ $BITS -eq 64 ];then
    mv /opt/ed-lvd/lvd-monitor-arm64 /opt/ed-lvd/lvd-monitor
else
    mv /opt/ed-lvd/lvd-monitor-armhf /opt/ed-lvd/lvd-monitor
fi

chmod +x /opt/ed-lvd/lvd-monitor

systemctl daemon-reload

exit 0